Name = input("Enter your name :")
r = int(input("Enter radius r : "))
l = int(input("Enter Length L :"))
b = int(input("Enter Breadth B :"))
A = 3.14*r*r
print("Area of circle :",A,end=" * ")
print(type(A))
Area = 2*(l+b)
print("Parameter of rectangle :",Area,end=" * ")
print(type(Area))
print("Name :",Name,end=" * ")
print(type(Name))
